spring:

  jpa:
    hibernate:
      ddl-auto: create-drop        # 테스트 후 테이블 삭제
    show-sql: true                 # SQL 쿼리 출력 (디버깅용)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # MySQL 문법 사용
        format_sql: true           # SQL 쿼리 포맷팅