# 1단계: 빌드 스테이지
FROM eclipse-temurin:21-jdk-alpine as builder

# 빌드 스테이지에서도 작업 디렉토리 설정
WORKDIR /app

# Gradle 빌드를 위한 파일들 복사
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src

# 실행 권한 부여 및 빌드
RUN chmod +x ./gradlew
RUN ./gradlew bootJar

# 2단계: 실행 스테이지
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

# 빌드 스테이지에서 생성된 JAR 파일만 복사
COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]