name: PURE_GRADLE_CD

on:
  workflow_run:
    workflows: ["PURE_GRADLE_CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: learn-githubAction-jar
          path: deploy # 아티팩트를 다운로드할 경로
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Deploy
        run: |
          echo "Deploying the application..."