name: PURE_GRADLE_CD

on:
  workflow_run:
    workflows: ["PURE_GRADLE_CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Deploy Start
